# Generated by Django 2.2.7 on 2019-11-26 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_cases_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cases',
            old_name='terms',
            new_name='terms_and_conditions',
        ),
    ]
