# Generated by Django 2.2.7 on 2019-11-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20191126_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='terms_and_conditions',
            field=models.BooleanField(null=True),
        ),
    ]
