# Generated by Django 2.2.7 on 2019-11-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_auto_20191126_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='I have read and agree to the terms of use and Privacy Policy'),
        ),
    ]
