# Generated by Django 2.2.7 on 2019-11-26 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_auto_20191126_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cases',
            name='state',
        ),
    ]
