# Generated by Django 2.2.7 on 2019-12-03 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_remove_cases_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='date',
            field=models.CharField(help_text='help text...', max_length=500, null=True, verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_comment', models.CharField(blank=True, help_text='Make your title attention-grabbing and informative.', max_length=255, null=True, verbose_name='Title comment ')),
                ('produit_comment', models.CharField(help_text='help text...', max_length=125, null=True, verbose_name='Produit comment ')),
                ('date_comment', models.CharField(help_text='help text...', max_length=500, null=True, verbose_name='Date comment')),
                ('context_comment', djrichtextfield.models.RichTextField(help_text='Son histoire, le contexte...', null=True, verbose_name='Context comment')),
                ('description_comment', djrichtextfield.models.RichTextField(help_text='help text...', null=True, verbose_name='Description comment')),
                ('diagnostic_comment', djrichtextfield.models.RichTextField(help_text='help text...', null=True, verbose_name='Diagnostic comment')),
                ('processus_comment', djrichtextfield.models.RichTextField(blank=True, help_text='help text...', null=True, verbose_name='Processus comment')),
                ('references_comment', djrichtextfield.models.RichTextField(help_text='help text...', null=True, verbose_name=' References comment')),
                ('abstract_comment', djrichtextfield.models.RichTextField(help_text='help text...', null=True, verbose_name=' Abstract comment')),
                ('comment_date', models.DateTimeField(default=django.utils.timezone.now, help_text='help text...', verbose_name='Date d’évaluation')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_case', to='stories.Cases')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
