# Generated by Django 2.2.7 on 2019-12-03 16:17

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_auto_20191203_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(editable=False)),
                ('date', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stories.Cases')),
            ],
            options={
                'unique_together': {('version', 'book')},
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='general_remarks',
            field=djrichtextfield.models.RichTextField(help_text='help text...', null=True, verbose_name=' Abstract comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='state_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='stories.State'),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
